services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: uvicorn --factory main:create_app --host 0.0.0.0 --port 8100 --reload --proxy-headers --forwarded-allow-ips="*"
    restart: unless-stopped