services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: uvicorn --factory main:create_app --host 192.168.220.66 --port 8100 --reload
    restart: unless-stopped